/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 furai.gltf
Author: 3DMAN (https://sketchfab.com/3dmanx888)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mazda-furai-fc01ffbdfba84943a80ca9ea17dfc67d
Title: Mazda Furai
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
function Model(props) {
  const { nodes, materials } = useGLTF('/models/MazdaFurai/furai.gltf')
  return (
    <group {...props} dispose={null} rotation={[-Math.PI / 3, 2, 1.57]} position={[0, 0, 0]}>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Mat_hotrinb.084_vehiclelights.bmp']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Mat_hotrinb.083_remap.bmp']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Mat_hotrinb.082_nero.bmp']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.BLACK} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Mat_hotrinb.085_vehiclelights.bmp']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Mat_hotrinb.086_vehiclelights.bmp']} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_11.geometry} material={materials['Mat_hotrinb.087_vehiclelights.bmp']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Mat_hotrinb.089_grid_d.bmp']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Mat_hotrinb.088_vehiclelights.bmp']} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_15.geometry} material={materials['Mat_hotrinb.080_badage_01.bmp']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Mat_hotrinb.078_nero.bmp']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.BLACK} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_21.geometry} material={materials['Mat_hotrinb.070_nero.bmp']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['Mat_hotrinb.069_carbon3_black.bmp']} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_24.geometry} material={materials['Mat_hotrinb.059_nero.bmp']} />
        <mesh geometry={nodes.Object_25.geometry} material={materials['Mat_hotrinb.060_remap.bmp']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['Mat_hotrinb.061_fur_main.bmp']} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.BLACK} />
        <mesh geometry={nodes.Object_28.geometry} material={materials['Mat_hotrinb.058_remap.bmp']} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_32.geometry} material={materials.BLACK} />
        <mesh geometry={nodes.Object_33.geometry} material={materials['Mat_hotrinb.023_vehiclelights.bmp']} />
        <mesh geometry={nodes.Object_34.geometry} material={materials['Mat_hotrinb.025_vehiclelights.bmp']} />
        <mesh geometry={nodes.Object_35.geometry} material={materials['Mat_hotrinb.022_vehiclelights.bmp']} />
        <mesh geometry={nodes.Object_36.geometry} material={materials['Mat_hotrinb.026_vehiclelights.bmp']} />
        <mesh geometry={nodes.Object_37.geometry} material={materials['Mat_hotrinb.021_fur_main.bmp']} />
        <mesh geometry={nodes.Object_38.geometry} material={materials['Mat_hotrinb.024_vehiclelights.bmp']} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.BLACK} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_41.geometry} material={materials['Mat_hotrinb.043_interior_lod0.bmp']} />
        <mesh geometry={nodes.Object_42.geometry} material={materials['Mat_hotrinb.042_fur_main.bmp']} />
        <mesh geometry={nodes.Object_43.geometry} material={materials['Mat_hotrinb.047_carbon3_black.bmp']} />
        <mesh geometry={nodes.Object_44.geometry} material={materials['Mat_hotrinb.041_remap.bmp']} />
        <mesh geometry={nodes.Object_45.geometry} material={materials['Mat_hotrinb.048_nero.bmp']} />
        <mesh geometry={nodes.Object_46.geometry} material={materials['Mat_hotrinb.044_vehiclelights.bmp']} />
        <mesh geometry={nodes.Object_47.geometry} material={materials['Mat_hotrinb.040_remap.bmp']} />
        <mesh geometry={nodes.Object_48.geometry} material={materials['Mat_hotrinb.046_fur_main.bmp']} />
        <mesh geometry={nodes.Object_49.geometry} material={materials['Mat_hotrinb.045_vehiclelights.bmp']} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_51.geometry} material={materials.BLACK} />
        <mesh geometry={nodes.Object_52.geometry} material={materials['Mat_hotrinb.051_carbon3_black.bmp']} />
        <mesh geometry={nodes.Object_53.geometry} material={materials['Mat_hotrinb.050_nero.bmp']} />
        <mesh geometry={nodes.Object_54.geometry} material={materials['Mat_hotrinb.052_fur_main.bmp']} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_56.geometry} material={materials['Mat_hotrinb.054_grid_d.bmp']} />
        <mesh geometry={nodes.Object_57.geometry} material={materials['Mat_hotrinb.053_glass.bmp']} />
        <mesh geometry={nodes.Object_58.geometry} material={materials['Mat_hotrinb.055_glass.bmp']} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_60.geometry} material={materials['Mat_hotrinb.123_glass.bmp']} />
        <mesh geometry={nodes.Object_61.geometry} material={materials['Mat_hotrinb.121_remap.bmp']} />
        <mesh geometry={nodes.Object_62.geometry} material={materials['Mat_hotrinb.122_fur_cabin.bmp']} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.BLACK} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_69.geometry} material={materials['Mat_hotrinb.108_remap.bmp']} />
        <mesh geometry={nodes.Object_70.geometry} material={materials['Mat_hotrinb.109_fur_cabin.bmp']} />
        <mesh geometry={nodes.Object_71.geometry} material={materials['Mat_hotrinb.110_glass.bmp']} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.BLACK} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_78.geometry} material={materials['Mat_hotrinb.035_carbon3_black.bmp']} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.BLACK} />
        <mesh geometry={nodes.Object_80.geometry} material={materials['Mat_hotrinb.036_remap.bmp']} />
        <mesh geometry={nodes.Object_81.geometry} material={materials['Mat_hotrinb.039_nero.bmp']} />
        <mesh geometry={nodes.Object_82.geometry} material={materials['Mat_hotrinb.038_remap.bmp']} />
        <mesh geometry={nodes.Object_83.geometry} material={materials['Mat_hotrinb.037_nero.bmp']} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_85.geometry} material={materials['Mat_hotrinb.140_hub.bmp']} />
        <mesh geometry={nodes.Object_86.geometry} material={materials['Mat_hotrinb.141_carbon3_black.bmp']} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_88.geometry} material={materials['Mat_hotrinb.137_carbon3_black.bmp']} />
        <mesh geometry={nodes.Object_89.geometry} material={materials['Mat_hotrinb.136_hub.bmp']} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_91.geometry} material={materials['Mat_hotrinb.139_carbon3_black.bmp']} />
        <mesh geometry={nodes.Object_92.geometry} material={materials['Mat_hotrinb.138_hub.bmp']} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_94.geometry} material={materials['Mat_hotrinb.135_carbon3_black.bmp']} />
        <mesh geometry={nodes.Object_95.geometry} material={materials['Mat_hotrinb.134_hub.bmp']} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_97.geometry} material={materials['Mat_hotrinb.028_carbon3_black.bmp']} />
        <mesh geometry={nodes.Object_98.geometry} material={materials['Mat_hotrinb.029_fur_cabin.bmp']} />
        <mesh geometry={nodes.Object_99.geometry} material={materials['Mat_hotrinb.027_nero.bmp']} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_101.geometry} material={materials['Mat_hotrinb.030_interior_lod0.bmp']} />
        <mesh geometry={nodes.Object_102.geometry} material={materials['Mat_hotrinb.032_remap.bmp']} />
        <mesh geometry={nodes.Object_103.geometry} material={materials['Mat_hotrinb.031_fur_main.bmp']} />
        <mesh geometry={nodes.Object_104.geometry} material={materials['Mat_hotrinb.033_carbon3_black.bmp']} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_106.geometry} material={materials['Mat_hotrinb.102_vehiclelights.bmp']} />
        <mesh geometry={nodes.Object_107.geometry} material={materials['Mat_hotrinb.101_vehiclelights.bmp']} />
        <mesh geometry={nodes.Object_108.geometry} material={materials['Mat_hotrinb.105_badage_01.bmp']} />
        <mesh geometry={nodes.Object_109.geometry} material={materials['Mat_hotrinb.103_vehiclelights.bmp']} />
        <mesh geometry={nodes.Object_110.geometry} material={materials['Mat_hotrinb.100_interior_lod0.bmp']} />
        <mesh geometry={nodes.Object_111.geometry} material={materials['Mat_hotrinb.104_carbon3_black.bmp']} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_113.geometry} material={materials['Mat_hotrinb_turismo_rotor.bmp']} />
        <mesh geometry={nodes.Object_114.geometry} material={materials['Mat_hotrinb.002_mfc_tireside.bmp']} />
        <mesh geometry={nodes.Object_115.geometry} material={materials.material} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_117.geometry} material={materials['Mat_hotrinb.006_mfc_tireside.bmp']} />
        <mesh geometry={nodes.Object_118.geometry} material={materials['Mat_hotrinb.004_turismo_rotor.bmp']} />
        <mesh geometry={nodes.Object_119.geometry} material={materials.material} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_121.geometry} material={materials['Mat_hotrinb.010_mfc_tireside.bmp']} />
        <mesh geometry={nodes.Object_122.geometry} material={materials['Mat_hotrinb.008_turismo_rotor.bmp']} />
        <mesh geometry={nodes.Object_123.geometry} material={materials.material} />
      </group>
      <group position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_125.geometry} material={materials['Mat_hotrinb.012_turismo_rotor.bmp']} />
        <mesh geometry={nodes.Object_126.geometry} material={materials['Mat_hotrinb.014_mfc_tireside.bmp']} />
        <mesh geometry={nodes.Object_127.geometry} material={materials['Mat_hotrinb.015_mfc_tireside.bmp']} />
        <mesh geometry={nodes.Object_128.geometry} material={materials['Mat_hotrinb.013_tread.bmp']} />
      </group>
      <mesh geometry={nodes.Object_19.geometry} material={materials['Mat_hotrinb.076_badage_01.bmp']} position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.BLACK} position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_65.geometry} material={materials['Mat_hotrinb.124_nero.bmp']} position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_67.geometry} material={materials['Mat_hotrinb.125_badage_01.bmp']} position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials['Mat_hotrinb.111_nero.bmp']} position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_76.geometry} material={materials['Mat_hotrinb.112_badage_01.bmp']} position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_130.geometry} material={materials['Mat_hotrinb.132_glass.bmp']} position={[0, 0.34, 0]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/MazdaFurai/furai.gltf')

export default Model