/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mazda7.gltf
Author: BadKarma™ (https://sketchfab.com/890244234)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/1992-mazda-rx-7-b76c1fb1185e469abc0110a8dc11e3cf
Title: 1992 Mazda RX-7
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model(props) {
  const { nodes, materials } = useGLTF('/models/Mazda7/mazda7.gltf')
  return (
    <group {...props} dispose={null} scale={0.3} >
      <group rotation={[-Math.PI / 3, 0, 1.57]} position={[2, 5, 6]}>
        <mesh geometry={nodes.Object_3.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.material_6} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.material_7} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.material_8} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.material_9} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.material_10} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.material_11} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.material_12} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.material_13} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.material_14} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.material_15} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.material_16} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.material_18} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.material_19} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.material_20} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.material_21} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.material_22} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.material_23} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.material_24} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.material_25} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.material_26} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.material_27} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.material_28} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.material_29} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.material_30} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Mazda7/mazda7.gltf')

export default Model