/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mazda3.gltf
Author: David_Holiday (https://sketchfab.com/David_Holiday)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mazda-3-0811f0d3785243a5ad05bd1b84457273
Title: Mazda-3
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model(props) {
  const { nodes, materials } = useGLTF('/models/Mazda3/mazda3.gltf')

  useEffect(() => {
    let material = materials.material_16
    material.color = {
      r: 0,
      b: 0,
      g: 0,
    }
    material.opacity = 0.6

  }, [materials])

  return (
    <group {...props} dispose={null} scale={0.01} rotation={[5.3, 1.60, 1.5]} position={[-0.2, 1.10, 0.4]}>
      <group position={[70.78, -38.05, 124.91]} rotation={[-Math.PI / 2, 0, 0]} scale={0.96}>
        <mesh geometry={nodes.wheel004_Material018_0.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.wheel004_Material016_0.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.wheel004_Material017_0.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.wheel004_Material015_0.geometry} material={materials['Material.015']} />
      </group>
      <group position={[-70.78, -38.05, 125.74]} rotation={[-Math.PI / 2, 0, 0]} scale={0.96}>
        <mesh geometry={nodes.wheel003_Material018_0.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.wheel003_Material016_0.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.wheel003_Material017_0.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.wheel003_Material015_0.geometry} material={materials['Material.015']} />
      </group>
      <group position={[71.23, -38.05, -123.34]} rotation={[-Math.PI / 2, 0, 0]} scale={0.96}>
        <mesh geometry={nodes.wheel002_Material018_0.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.wheel002_Material016_0.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.wheel002_Material017_0.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.wheel002_Material015_0.geometry} material={materials['Material.015']} />
      </group>
      <group position={[-71.23, -38.05, -123.34]} rotation={[-Math.PI / 2, 0, 0]} scale={0.96}>
        <mesh geometry={nodes.wheel001_Material018_0.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.wheel001_Material016_0.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.wheel001_Material017_0.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.wheel001_Material015_0.geometry} material={materials['Material.015']} />
      </group>
      <mesh geometry={nodes.cal_Material019_0.geometry} material={materials['Material.019']} position={[71.23, -38.05, 125.32]} rotation={[0.27, -0.29, 0.08]} scale={0.9} />
      <mesh geometry={nodes.object_Material010_0.geometry} material={materials['Material.010']} position={[-1.31, 20.51, -196.87]} scale={0.1} />
      <mesh geometry={nodes.object001_bod_0.geometry} material={materials.material} position={[0, 7.47, -0.1]} scale={0.1} />
      <mesh geometry={nodes.object002_Material009_0.geometry} material={materials['Material.009']} position={[-0.27, 18.32, -179]} scale={0.1} />
      <mesh geometry={nodes.object003_chrome_0.geometry} material={materials.chrome} position={[0.17, -1.72, 3.27]} scale={0.1} />
      <mesh geometry={nodes.object005_Material003_0.geometry} material={materials['Material.003']} position={[-0.26, -10.14, 9.87]} scale={0.1} />
      <mesh geometry={nodes.object007_Material007_0.geometry} material={materials['Material.007']} position={[0.17, -9.62, -1.13]} scale={0.1} />
      <mesh geometry={nodes.object008_Material005_0.geometry} material={materials['Material.005']} position={[0.01, 11.29, 9.01]} scale={0.1} />
      <mesh geometry={nodes.object009_Material002_0.geometry} material={materials['Material.002']} position={[0, -1.77, 8.39]} scale={0.1} />
      <mesh geometry={nodes.object010_shiny_0.geometry} material={materials.shiny} position={[-0.31, -6.46, 10.84]} scale={0.1} />
      <mesh geometry={nodes.object011_Material004_0.geometry} material={materials['Material.004']} position={[-0.41, -17, 206.4]} scale={0.1} />
      <mesh geometry={nodes.object012_Material008_0.geometry} material={materials['Material.008']} position={[0.22, -27.8, 187.17]} scale={0.1} />
      <mesh geometry={nodes.object013_gl_0.geometry} material={materials.material_16} position={[-0.04, 42.7, -36.06]} scale={0.1} />
      <mesh geometry={nodes.object014_Material006_0.geometry} material={materials['Material.006']} position={[0.06, 4.72, 24.08]} scale={0.1} />
      <mesh geometry={nodes.object015_Material001_0.geometry} material={materials['Material.001']} position={[0.17, -2.45, -2.65]} scale={0.1} />
      <mesh geometry={nodes.object004_chrome_0.geometry} material={materials.chrome} position={[-0.06, 8.44, 3.27]} scale={0.1} />
      <mesh geometry={nodes.object016_chrome_0.geometry} material={materials.chrome} position={[0, 26.63, 39.06]} scale={0.1} />
      <mesh geometry={nodes.cal001_Material019_0.geometry} material={materials['Material.019']} position={[-71.23, -38.05, 125.32]} rotation={[0.27, -0.29, 0.08]} scale={[-0.9, 0.9, 0.9]} />
      <mesh geometry={nodes.cal002_Material019_0.geometry} material={materials['Material.019']} position={[-71.23, -38.05, -123.34]} rotation={[0.26, 0, 0]} scale={[-0.9, 0.9, 0.9]} />
      <mesh geometry={nodes.cal003_Material019_0.geometry} material={materials['Material.019']} position={[71.23, -38.05, -123.34]} rotation={[0.26, 0, 0]} scale={0.9} />
      <mesh geometry={nodes.interior_Material011_0.geometry} material={materials['Material.011']} position={[-8.58, 8.91, -46.11]} scale={[0.83, 0.86, 0.86]} />
    </group>
  )
}

useGLTF.preload('/models/Mazda3/mazda3.gltf')

export default Model
